source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
